services:
  splunk-base:
    image: splunk/splunk:latest
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=changeme
    volumes:
      - splunk-data:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    networks:
      lab-net:
        ipv4_address: 192.168.255.100
    ports:
      - "8000:8000"
      - "9997:9997"
      - "514:514"

  dvwa:
    image: ashokkumarl/dvwa:latest
    container_name: dvwa
    ports:
      - "8080:80"
    networks:
      lab-net:
        ipv4_address: 192.168.255.101
    volumes:
      - dvwa-ubuntu-data:/opt/var
      - dvwa-ubuntu-db:/var/lib/mysql
networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.255.0/24

volumes:
  splunk-data:
  splunk-etc:
  dvwa-ubuntu-data:
  dvwa-ubuntu-db: