#version: '3.9'

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.254.0/24

volumes:
  splunk-data:
  splunk-etc:
  dvwa-ubuntu-data:
  dvwa-ubuntu-db:

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    hostname: splunk
    ports:
      - "8000:8000"   # Splunk Web UI
      - "514:514" # Syslog TCP
      - "9997:9997"  # Splunk HEC and Forwarding
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=changeme
    networks:
      lab-net:
        ipv4_address: 192.168.254.100
    volumes:
      - splunk-data:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc



  dvwa:
    image: ashokkumarl/dvwa:latest
    container_name: dvwa
    hostname: dvwa
    ports:
      - "8080:80"    # DVWA Web UI
    networks:
      lab-net:
        ipv4_address: 192.168.254.101
    volumes:
      - dvwa-ubuntu-data:/opt/var
      - dvwa-ubuntu-db:/var/lib/mysql
